const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

/**
 * Stores the per-file analysis fragment generated by the AI.
 * fileHash allows skipping re-analysis of unchanged files.
 */
const AiFragment = sequelize.define('AiFragment', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  systemId: {
    type: DataTypes.UUID,
    allowNull: false,
  },
  // diagramId can be null if the diagram was later deleted
  diagramId: {
    type: DataTypes.UUID,
    allowNull: true,
  },
  filename: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  originalName: {
    type: DataTypes.STRING,
  },
  // SHA-256 of the file content — used to skip re-analysis of unchanged files
  fileHash: {
    type: DataTypes.STRING(64),
    allowNull: false,
  },
  // Markdown fragment analysis produced by the AI for this single file
  content: {
    type: DataTypes.TEXT,
    allowNull: false,
  },
}, {
  indexes: [
    { fields: ['systemId'] },
    { fields: ['fileHash'] },
    { unique: true, fields: ['systemId', 'diagramId'] },
  ],
});

module.exports = AiFragment;
